# -*- coding: utf-8 -*-
"""__init__.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BcwrDU5yktsFqiFUDzYBk9c1QWFTjYar
"""

from gym_switching.envs.switching_env import SwitchingEnv