# -*- coding: utf-8 -*-
"""__init__.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BcwrDU5yktsFqiFUDzYBk9c1QWFTjYar
"""

from gym.envs.registration import register

register(
    id='switching-v0',
    entry_point='gym_switching.envs:SwitchingEnv',
)
© 2022 GitHub, Inc.
Terms
Privacy
Security